// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox inputHeaderBox1;
    
    private Gtk.Label inputFilesLabel;
    
    private Gtk.HBox separatorBox1;
    
    private Gtk.HSeparator hseparator1;
    
    private Gtk.HBox filebox1;
    
    private Gtk.Label fileLabel1;
    
    private Gtk.EventBox eventbox1;
    
    private Gtk.FileChooserButton file1;
    
    private Gtk.Button removeButton1;
    
    private Gtk.Button addButton1;
    
    private Gtk.HBox filebox2;
    
    private Gtk.Label fileLabel2;
    
    private Gtk.EventBox eventbox2;
    
    private Gtk.FileChooserButton file2;
    
    private Gtk.Button removeButton2;
    
    private Gtk.Button addButton2;
    
    private Gtk.HBox filebox3;
    
    private Gtk.Label fileLabel3;
    
    private Gtk.EventBox eventbox3;
    
    private Gtk.FileChooserButton file3;
    
    private Gtk.Button removeButton3;
    
    private Gtk.Button addButton3;
    
    private Gtk.HBox filebox4;
    
    private Gtk.Label fileLabel4;
    
    private Gtk.EventBox eventbox4;
    
    private Gtk.FileChooserButton file4;
    
    private Gtk.Button removeButton4;
    
    private Gtk.Button addButton4;
    
    private Gtk.HBox filebox5;
    
    private Gtk.Label fileLabel5;
    
    private Gtk.EventBox eventbox5;
    
    private Gtk.FileChooserButton file5;
    
    private Gtk.Button removeButton5;
    
    private Gtk.Button addButton5;
    
    private Gtk.HBox filebox6;
    
    private Gtk.Label fileLabel6;
    
    private Gtk.EventBox eventbox6;
    
    private Gtk.FileChooserButton file6;
    
    private Gtk.Button removeButton6;
    
    private Gtk.Button addButton6;
    
    private Gtk.HBox filebox7;
    
    private Gtk.Label fileLabel7;
    
    private Gtk.EventBox eventbox7;
    
    private Gtk.FileChooserButton file7;
    
    private Gtk.Button removeButton7;
    
    private Gtk.Button addButton7;
    
    private Gtk.HBox filebox8;
    
    private Gtk.Label fileLabel8;
    
    private Gtk.EventBox eventbox8;
    
    private Gtk.FileChooserButton file8;
    
    private Gtk.Button removeButton8;
    
    private Gtk.Button addButton8;
    
    private Gtk.HBox filebox9;
    
    private Gtk.Label fileLabel9;
    
    private Gtk.EventBox eventbox9;
    
    private Gtk.FileChooserButton file9;
    
    private Gtk.Button removeButton9;
    
    private Gtk.Button addButton9;
    
    private Gtk.HBox filebox10;
    
    private Gtk.Label fileLabel10;
    
    private Gtk.EventBox eventbox10;
    
    private Gtk.FileChooserButton file10;
    
    private Gtk.Button removeButton10;
    
    private Gtk.Button addButton10;
    
    private Gtk.Label spacer4;
    
    private Gtk.HBox hbox20;
    
    private Gtk.Label mergeOptionsLabel;
    
    private Gtk.HBox hbox21;
    
    private Gtk.HSeparator hseparator3;
    
    private Gtk.HBox hbox31;
    
    private Gtk.Label additionalLabel;
    
    private Gtk.EventBox eventbox11;
    
    private Gtk.FileChooserButton filechooserbutton20;
    
    private Gtk.HBox hbox32;
    
    private Gtk.Label inputAudioLabel;
    
    private Gtk.SpinButton inputAudioIndex;
    
    private Gtk.SpinButton outputAudioIndex;
    
    private Gtk.Label outputAudioLabel;
    
    private Gtk.Label spacer5;
    
    private Gtk.HBox hbox22;
    
    private Gtk.Label outputFileLabel;
    
    private Gtk.HBox hbox23;
    
    private Gtk.HSeparator hseparator4;
    
    private Gtk.HBox hbox26;
    
    private Gtk.Button mergeActionButton;
    
    private Gtk.Label spacer6;
    
    private Gtk.HBox hbox28;
    
    private Gtk.Label progressLabel;
    
    private Gtk.HBox hbox29;
    
    private Gtk.HSeparator hseparator7;
    
    private Gtk.HBox hbox30;
    
    private Gtk.ProgressBar mergeProgressBar1;
    
    private Gtk.Label spacer7;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MonoMerge");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.inputHeaderBox1 = new Gtk.HBox();
        this.inputHeaderBox1.Name = "inputHeaderBox1";
        this.inputHeaderBox1.Spacing = 6;
        // Container child inputHeaderBox1.Gtk.Box+BoxChild
        this.inputFilesLabel = new Gtk.Label();
        this.inputFilesLabel.Name = "inputFilesLabel";
        this.inputFilesLabel.LabelProp = Mono.Unix.Catalog.GetString("Input files");
        this.inputHeaderBox1.Add(this.inputFilesLabel);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.inputHeaderBox1[this.inputFilesLabel]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        w3.Padding = ((uint)(6));
        this.vbox1.Add(this.inputHeaderBox1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.inputHeaderBox1]));
        w4.Position = 1;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.separatorBox1 = new Gtk.HBox();
        this.separatorBox1.Name = "separatorBox1";
        this.separatorBox1.Spacing = 6;
        // Container child separatorBox1.Gtk.Box+BoxChild
        this.hseparator1 = new Gtk.HSeparator();
        this.hseparator1.Name = "hseparator1";
        this.separatorBox1.Add(this.hseparator1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.separatorBox1[this.hseparator1]));
        w5.Position = 0;
        w5.Padding = ((uint)(6));
        this.vbox1.Add(this.separatorBox1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.separatorBox1]));
        w6.Position = 2;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox1 = new Gtk.HBox();
        this.filebox1.Name = "filebox1";
        this.filebox1.Spacing = 6;
        // Container child filebox1.Gtk.Box+BoxChild
        this.fileLabel1 = new Gtk.Label();
        this.fileLabel1.WidthRequest = 40;
        this.fileLabel1.Name = "fileLabel1";
        this.fileLabel1.LabelProp = Mono.Unix.Catalog.GetString("File 1");
        this.filebox1.Add(this.fileLabel1);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.filebox1[this.fileLabel1]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        w7.Padding = ((uint)(6));
        // Container child filebox1.Gtk.Box+BoxChild
        this.eventbox1 = new Gtk.EventBox();
        this.eventbox1.Name = "eventbox1";
        // Container child eventbox1.Gtk.Container+ContainerChild
        this.file1 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file1.TooltipMarkup = "Drag & drop here";
        this.file1.WidthRequest = 180;
        this.file1.Name = "file1";
        this.eventbox1.Add(this.file1);
        this.filebox1.Add(this.eventbox1);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.filebox1[this.eventbox1]));
        w9.Position = 1;
        // Container child filebox1.Gtk.Box+BoxChild
        this.removeButton1 = new Gtk.Button();
        this.removeButton1.Sensitive = false;
        this.removeButton1.CanFocus = true;
        this.removeButton1.Name = "removeButton1";
        this.removeButton1.UseUnderline = true;
        // Container child removeButton1.Gtk.Container+ContainerChild
        Gtk.Alignment w10 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w11 = new Gtk.HBox();
        w11.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w12 = new Gtk.Image();
        w12.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w11.Add(w12);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w14 = new Gtk.Label();
        w11.Add(w14);
        w10.Add(w11);
        this.removeButton1.Add(w10);
        this.filebox1.Add(this.removeButton1);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.filebox1[this.removeButton1]));
        w18.Position = 2;
        w18.Expand = false;
        w18.Fill = false;
        // Container child filebox1.Gtk.Box+BoxChild
        this.addButton1 = new Gtk.Button();
        this.addButton1.Sensitive = false;
        this.addButton1.CanFocus = true;
        this.addButton1.Name = "addButton1";
        this.addButton1.UseUnderline = true;
        // Container child addButton1.Gtk.Container+ContainerChild
        Gtk.Alignment w19 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w20 = new Gtk.HBox();
        w20.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w21 = new Gtk.Image();
        w21.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w20.Add(w21);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w23 = new Gtk.Label();
        w20.Add(w23);
        w19.Add(w20);
        this.addButton1.Add(w19);
        this.filebox1.Add(this.addButton1);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.filebox1[this.addButton1]));
        w27.Position = 3;
        w27.Expand = false;
        w27.Fill = false;
        w27.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox1);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox1]));
        w28.Position = 3;
        w28.Expand = false;
        w28.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox2 = new Gtk.HBox();
        this.filebox2.Name = "filebox2";
        this.filebox2.Spacing = 6;
        // Container child filebox2.Gtk.Box+BoxChild
        this.fileLabel2 = new Gtk.Label();
        this.fileLabel2.WidthRequest = 40;
        this.fileLabel2.Name = "fileLabel2";
        this.fileLabel2.LabelProp = Mono.Unix.Catalog.GetString("File 2");
        this.filebox2.Add(this.fileLabel2);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.filebox2[this.fileLabel2]));
        w29.Position = 0;
        w29.Expand = false;
        w29.Fill = false;
        w29.Padding = ((uint)(6));
        // Container child filebox2.Gtk.Box+BoxChild
        this.eventbox2 = new Gtk.EventBox();
        this.eventbox2.Name = "eventbox2";
        // Container child eventbox2.Gtk.Container+ContainerChild
        this.file2 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file2.TooltipMarkup = "Drag & drop here";
        this.file2.WidthRequest = 180;
        this.file2.Name = "file2";
        this.eventbox2.Add(this.file2);
        this.filebox2.Add(this.eventbox2);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.filebox2[this.eventbox2]));
        w31.Position = 1;
        // Container child filebox2.Gtk.Box+BoxChild
        this.removeButton2 = new Gtk.Button();
        this.removeButton2.Sensitive = false;
        this.removeButton2.CanFocus = true;
        this.removeButton2.Name = "removeButton2";
        this.removeButton2.UseUnderline = true;
        // Container child removeButton2.Gtk.Container+ContainerChild
        Gtk.Alignment w32 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w33 = new Gtk.HBox();
        w33.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w34 = new Gtk.Image();
        w34.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w33.Add(w34);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w36 = new Gtk.Label();
        w33.Add(w36);
        w32.Add(w33);
        this.removeButton2.Add(w32);
        this.filebox2.Add(this.removeButton2);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.filebox2[this.removeButton2]));
        w40.Position = 2;
        w40.Expand = false;
        w40.Fill = false;
        // Container child filebox2.Gtk.Box+BoxChild
        this.addButton2 = new Gtk.Button();
        this.addButton2.CanFocus = true;
        this.addButton2.Name = "addButton2";
        this.addButton2.UseUnderline = true;
        // Container child addButton2.Gtk.Container+ContainerChild
        Gtk.Alignment w41 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w42 = new Gtk.HBox();
        w42.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w43 = new Gtk.Image();
        w43.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w42.Add(w43);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w45 = new Gtk.Label();
        w42.Add(w45);
        w41.Add(w42);
        this.addButton2.Add(w41);
        this.filebox2.Add(this.addButton2);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.filebox2[this.addButton2]));
        w49.Position = 3;
        w49.Expand = false;
        w49.Fill = false;
        w49.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox2);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox2]));
        w50.Position = 4;
        w50.Expand = false;
        w50.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox3 = new Gtk.HBox();
        this.filebox3.Name = "filebox3";
        this.filebox3.Spacing = 6;
        // Container child filebox3.Gtk.Box+BoxChild
        this.fileLabel3 = new Gtk.Label();
        this.fileLabel3.WidthRequest = 40;
        this.fileLabel3.Name = "fileLabel3";
        this.fileLabel3.LabelProp = Mono.Unix.Catalog.GetString("File 3");
        this.filebox3.Add(this.fileLabel3);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.filebox3[this.fileLabel3]));
        w51.Position = 0;
        w51.Expand = false;
        w51.Fill = false;
        w51.Padding = ((uint)(6));
        // Container child filebox3.Gtk.Box+BoxChild
        this.eventbox3 = new Gtk.EventBox();
        this.eventbox3.Name = "eventbox3";
        // Container child eventbox3.Gtk.Container+ContainerChild
        this.file3 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file3.TooltipMarkup = "Drag & drop here";
        this.file3.WidthRequest = 180;
        this.file3.Name = "file3";
        this.eventbox3.Add(this.file3);
        this.filebox3.Add(this.eventbox3);
        Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.filebox3[this.eventbox3]));
        w53.Position = 1;
        // Container child filebox3.Gtk.Box+BoxChild
        this.removeButton3 = new Gtk.Button();
        this.removeButton3.CanFocus = true;
        this.removeButton3.Name = "removeButton3";
        this.removeButton3.UseUnderline = true;
        // Container child removeButton3.Gtk.Container+ContainerChild
        Gtk.Alignment w54 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w55 = new Gtk.HBox();
        w55.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w56 = new Gtk.Image();
        w56.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w55.Add(w56);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w58 = new Gtk.Label();
        w55.Add(w58);
        w54.Add(w55);
        this.removeButton3.Add(w54);
        this.filebox3.Add(this.removeButton3);
        Gtk.Box.BoxChild w62 = ((Gtk.Box.BoxChild)(this.filebox3[this.removeButton3]));
        w62.Position = 2;
        w62.Expand = false;
        w62.Fill = false;
        // Container child filebox3.Gtk.Box+BoxChild
        this.addButton3 = new Gtk.Button();
        this.addButton3.CanFocus = true;
        this.addButton3.Name = "addButton3";
        this.addButton3.UseUnderline = true;
        // Container child addButton3.Gtk.Container+ContainerChild
        Gtk.Alignment w63 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w64 = new Gtk.HBox();
        w64.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w65 = new Gtk.Image();
        w65.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w64.Add(w65);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w67 = new Gtk.Label();
        w64.Add(w67);
        w63.Add(w64);
        this.addButton3.Add(w63);
        this.filebox3.Add(this.addButton3);
        Gtk.Box.BoxChild w71 = ((Gtk.Box.BoxChild)(this.filebox3[this.addButton3]));
        w71.Position = 3;
        w71.Expand = false;
        w71.Fill = false;
        w71.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox3);
        Gtk.Box.BoxChild w72 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox3]));
        w72.Position = 5;
        w72.Expand = false;
        w72.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox4 = new Gtk.HBox();
        this.filebox4.Name = "filebox4";
        this.filebox4.Spacing = 6;
        // Container child filebox4.Gtk.Box+BoxChild
        this.fileLabel4 = new Gtk.Label();
        this.fileLabel4.WidthRequest = 40;
        this.fileLabel4.Name = "fileLabel4";
        this.fileLabel4.LabelProp = Mono.Unix.Catalog.GetString("File 4");
        this.filebox4.Add(this.fileLabel4);
        Gtk.Box.BoxChild w73 = ((Gtk.Box.BoxChild)(this.filebox4[this.fileLabel4]));
        w73.Position = 0;
        w73.Expand = false;
        w73.Fill = false;
        w73.Padding = ((uint)(6));
        // Container child filebox4.Gtk.Box+BoxChild
        this.eventbox4 = new Gtk.EventBox();
        this.eventbox4.Name = "eventbox4";
        // Container child eventbox4.Gtk.Container+ContainerChild
        this.file4 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file4.TooltipMarkup = "Drag & drop here";
        this.file4.WidthRequest = 180;
        this.file4.Name = "file4";
        this.eventbox4.Add(this.file4);
        this.filebox4.Add(this.eventbox4);
        Gtk.Box.BoxChild w75 = ((Gtk.Box.BoxChild)(this.filebox4[this.eventbox4]));
        w75.Position = 1;
        // Container child filebox4.Gtk.Box+BoxChild
        this.removeButton4 = new Gtk.Button();
        this.removeButton4.CanFocus = true;
        this.removeButton4.Name = "removeButton4";
        this.removeButton4.UseUnderline = true;
        // Container child removeButton4.Gtk.Container+ContainerChild
        Gtk.Alignment w76 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w77 = new Gtk.HBox();
        w77.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w78 = new Gtk.Image();
        w78.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w77.Add(w78);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w80 = new Gtk.Label();
        w77.Add(w80);
        w76.Add(w77);
        this.removeButton4.Add(w76);
        this.filebox4.Add(this.removeButton4);
        Gtk.Box.BoxChild w84 = ((Gtk.Box.BoxChild)(this.filebox4[this.removeButton4]));
        w84.Position = 2;
        w84.Expand = false;
        w84.Fill = false;
        // Container child filebox4.Gtk.Box+BoxChild
        this.addButton4 = new Gtk.Button();
        this.addButton4.CanFocus = true;
        this.addButton4.Name = "addButton4";
        this.addButton4.UseUnderline = true;
        // Container child addButton4.Gtk.Container+ContainerChild
        Gtk.Alignment w85 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w86 = new Gtk.HBox();
        w86.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w87 = new Gtk.Image();
        w87.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w86.Add(w87);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w89 = new Gtk.Label();
        w86.Add(w89);
        w85.Add(w86);
        this.addButton4.Add(w85);
        this.filebox4.Add(this.addButton4);
        Gtk.Box.BoxChild w93 = ((Gtk.Box.BoxChild)(this.filebox4[this.addButton4]));
        w93.Position = 3;
        w93.Expand = false;
        w93.Fill = false;
        w93.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox4);
        Gtk.Box.BoxChild w94 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox4]));
        w94.Position = 6;
        w94.Expand = false;
        w94.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox5 = new Gtk.HBox();
        this.filebox5.Name = "filebox5";
        this.filebox5.Spacing = 6;
        // Container child filebox5.Gtk.Box+BoxChild
        this.fileLabel5 = new Gtk.Label();
        this.fileLabel5.WidthRequest = 40;
        this.fileLabel5.Name = "fileLabel5";
        this.fileLabel5.LabelProp = Mono.Unix.Catalog.GetString("File 5");
        this.filebox5.Add(this.fileLabel5);
        Gtk.Box.BoxChild w95 = ((Gtk.Box.BoxChild)(this.filebox5[this.fileLabel5]));
        w95.Position = 0;
        w95.Expand = false;
        w95.Fill = false;
        w95.Padding = ((uint)(6));
        // Container child filebox5.Gtk.Box+BoxChild
        this.eventbox5 = new Gtk.EventBox();
        this.eventbox5.Name = "eventbox5";
        // Container child eventbox5.Gtk.Container+ContainerChild
        this.file5 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file5.TooltipMarkup = "Drag & drop here";
        this.file5.WidthRequest = 180;
        this.file5.Name = "file5";
        this.eventbox5.Add(this.file5);
        this.filebox5.Add(this.eventbox5);
        Gtk.Box.BoxChild w97 = ((Gtk.Box.BoxChild)(this.filebox5[this.eventbox5]));
        w97.Position = 1;
        // Container child filebox5.Gtk.Box+BoxChild
        this.removeButton5 = new Gtk.Button();
        this.removeButton5.CanFocus = true;
        this.removeButton5.Name = "removeButton5";
        this.removeButton5.UseUnderline = true;
        // Container child removeButton5.Gtk.Container+ContainerChild
        Gtk.Alignment w98 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w99 = new Gtk.HBox();
        w99.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w100 = new Gtk.Image();
        w100.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w99.Add(w100);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w102 = new Gtk.Label();
        w99.Add(w102);
        w98.Add(w99);
        this.removeButton5.Add(w98);
        this.filebox5.Add(this.removeButton5);
        Gtk.Box.BoxChild w106 = ((Gtk.Box.BoxChild)(this.filebox5[this.removeButton5]));
        w106.Position = 2;
        w106.Expand = false;
        w106.Fill = false;
        // Container child filebox5.Gtk.Box+BoxChild
        this.addButton5 = new Gtk.Button();
        this.addButton5.CanFocus = true;
        this.addButton5.Name = "addButton5";
        this.addButton5.UseUnderline = true;
        // Container child addButton5.Gtk.Container+ContainerChild
        Gtk.Alignment w107 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w108 = new Gtk.HBox();
        w108.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w109 = new Gtk.Image();
        w109.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w108.Add(w109);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w111 = new Gtk.Label();
        w108.Add(w111);
        w107.Add(w108);
        this.addButton5.Add(w107);
        this.filebox5.Add(this.addButton5);
        Gtk.Box.BoxChild w115 = ((Gtk.Box.BoxChild)(this.filebox5[this.addButton5]));
        w115.Position = 3;
        w115.Expand = false;
        w115.Fill = false;
        w115.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox5);
        Gtk.Box.BoxChild w116 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox5]));
        w116.Position = 7;
        w116.Expand = false;
        w116.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox6 = new Gtk.HBox();
        this.filebox6.Name = "filebox6";
        this.filebox6.Spacing = 6;
        // Container child filebox6.Gtk.Box+BoxChild
        this.fileLabel6 = new Gtk.Label();
        this.fileLabel6.WidthRequest = 40;
        this.fileLabel6.Name = "fileLabel6";
        this.fileLabel6.LabelProp = Mono.Unix.Catalog.GetString("File 6");
        this.filebox6.Add(this.fileLabel6);
        Gtk.Box.BoxChild w117 = ((Gtk.Box.BoxChild)(this.filebox6[this.fileLabel6]));
        w117.Position = 0;
        w117.Expand = false;
        w117.Fill = false;
        w117.Padding = ((uint)(6));
        // Container child filebox6.Gtk.Box+BoxChild
        this.eventbox6 = new Gtk.EventBox();
        this.eventbox6.Name = "eventbox6";
        // Container child eventbox6.Gtk.Container+ContainerChild
        this.file6 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file6.TooltipMarkup = "Drag & drop here";
        this.file6.WidthRequest = 180;
        this.file6.Name = "file6";
        this.eventbox6.Add(this.file6);
        this.filebox6.Add(this.eventbox6);
        Gtk.Box.BoxChild w119 = ((Gtk.Box.BoxChild)(this.filebox6[this.eventbox6]));
        w119.Position = 1;
        // Container child filebox6.Gtk.Box+BoxChild
        this.removeButton6 = new Gtk.Button();
        this.removeButton6.CanFocus = true;
        this.removeButton6.Name = "removeButton6";
        this.removeButton6.UseUnderline = true;
        // Container child removeButton6.Gtk.Container+ContainerChild
        Gtk.Alignment w120 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w121 = new Gtk.HBox();
        w121.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w122 = new Gtk.Image();
        w122.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w121.Add(w122);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w124 = new Gtk.Label();
        w121.Add(w124);
        w120.Add(w121);
        this.removeButton6.Add(w120);
        this.filebox6.Add(this.removeButton6);
        Gtk.Box.BoxChild w128 = ((Gtk.Box.BoxChild)(this.filebox6[this.removeButton6]));
        w128.Position = 2;
        w128.Expand = false;
        w128.Fill = false;
        // Container child filebox6.Gtk.Box+BoxChild
        this.addButton6 = new Gtk.Button();
        this.addButton6.CanFocus = true;
        this.addButton6.Name = "addButton6";
        this.addButton6.UseUnderline = true;
        // Container child addButton6.Gtk.Container+ContainerChild
        Gtk.Alignment w129 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w130 = new Gtk.HBox();
        w130.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w131 = new Gtk.Image();
        w131.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w130.Add(w131);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w133 = new Gtk.Label();
        w130.Add(w133);
        w129.Add(w130);
        this.addButton6.Add(w129);
        this.filebox6.Add(this.addButton6);
        Gtk.Box.BoxChild w137 = ((Gtk.Box.BoxChild)(this.filebox6[this.addButton6]));
        w137.Position = 3;
        w137.Expand = false;
        w137.Fill = false;
        w137.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox6);
        Gtk.Box.BoxChild w138 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox6]));
        w138.Position = 8;
        w138.Expand = false;
        w138.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox7 = new Gtk.HBox();
        this.filebox7.Name = "filebox7";
        this.filebox7.Spacing = 6;
        // Container child filebox7.Gtk.Box+BoxChild
        this.fileLabel7 = new Gtk.Label();
        this.fileLabel7.WidthRequest = 40;
        this.fileLabel7.Name = "fileLabel7";
        this.fileLabel7.LabelProp = Mono.Unix.Catalog.GetString("File 7");
        this.filebox7.Add(this.fileLabel7);
        Gtk.Box.BoxChild w139 = ((Gtk.Box.BoxChild)(this.filebox7[this.fileLabel7]));
        w139.Position = 0;
        w139.Expand = false;
        w139.Fill = false;
        w139.Padding = ((uint)(6));
        // Container child filebox7.Gtk.Box+BoxChild
        this.eventbox7 = new Gtk.EventBox();
        this.eventbox7.Name = "eventbox7";
        // Container child eventbox7.Gtk.Container+ContainerChild
        this.file7 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file7.TooltipMarkup = "Drag & drop here";
        this.file7.WidthRequest = 180;
        this.file7.Name = "file7";
        this.eventbox7.Add(this.file7);
        this.filebox7.Add(this.eventbox7);
        Gtk.Box.BoxChild w141 = ((Gtk.Box.BoxChild)(this.filebox7[this.eventbox7]));
        w141.Position = 1;
        // Container child filebox7.Gtk.Box+BoxChild
        this.removeButton7 = new Gtk.Button();
        this.removeButton7.CanFocus = true;
        this.removeButton7.Name = "removeButton7";
        this.removeButton7.UseUnderline = true;
        // Container child removeButton7.Gtk.Container+ContainerChild
        Gtk.Alignment w142 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w143 = new Gtk.HBox();
        w143.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w144 = new Gtk.Image();
        w144.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w143.Add(w144);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w146 = new Gtk.Label();
        w143.Add(w146);
        w142.Add(w143);
        this.removeButton7.Add(w142);
        this.filebox7.Add(this.removeButton7);
        Gtk.Box.BoxChild w150 = ((Gtk.Box.BoxChild)(this.filebox7[this.removeButton7]));
        w150.Position = 2;
        w150.Expand = false;
        w150.Fill = false;
        // Container child filebox7.Gtk.Box+BoxChild
        this.addButton7 = new Gtk.Button();
        this.addButton7.CanFocus = true;
        this.addButton7.Name = "addButton7";
        this.addButton7.UseUnderline = true;
        // Container child addButton7.Gtk.Container+ContainerChild
        Gtk.Alignment w151 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w152 = new Gtk.HBox();
        w152.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w153 = new Gtk.Image();
        w153.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w152.Add(w153);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w155 = new Gtk.Label();
        w152.Add(w155);
        w151.Add(w152);
        this.addButton7.Add(w151);
        this.filebox7.Add(this.addButton7);
        Gtk.Box.BoxChild w159 = ((Gtk.Box.BoxChild)(this.filebox7[this.addButton7]));
        w159.Position = 3;
        w159.Expand = false;
        w159.Fill = false;
        w159.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox7);
        Gtk.Box.BoxChild w160 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox7]));
        w160.Position = 9;
        w160.Expand = false;
        w160.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox8 = new Gtk.HBox();
        this.filebox8.Name = "filebox8";
        this.filebox8.Spacing = 6;
        // Container child filebox8.Gtk.Box+BoxChild
        this.fileLabel8 = new Gtk.Label();
        this.fileLabel8.WidthRequest = 40;
        this.fileLabel8.Name = "fileLabel8";
        this.fileLabel8.LabelProp = Mono.Unix.Catalog.GetString("File 8");
        this.filebox8.Add(this.fileLabel8);
        Gtk.Box.BoxChild w161 = ((Gtk.Box.BoxChild)(this.filebox8[this.fileLabel8]));
        w161.Position = 0;
        w161.Expand = false;
        w161.Fill = false;
        w161.Padding = ((uint)(6));
        // Container child filebox8.Gtk.Box+BoxChild
        this.eventbox8 = new Gtk.EventBox();
        this.eventbox8.Name = "eventbox8";
        // Container child eventbox8.Gtk.Container+ContainerChild
        this.file8 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file8.TooltipMarkup = "Drag & drop here";
        this.file8.WidthRequest = 180;
        this.file8.Name = "file8";
        this.eventbox8.Add(this.file8);
        this.filebox8.Add(this.eventbox8);
        Gtk.Box.BoxChild w163 = ((Gtk.Box.BoxChild)(this.filebox8[this.eventbox8]));
        w163.Position = 1;
        // Container child filebox8.Gtk.Box+BoxChild
        this.removeButton8 = new Gtk.Button();
        this.removeButton8.CanFocus = true;
        this.removeButton8.Name = "removeButton8";
        this.removeButton8.UseUnderline = true;
        // Container child removeButton8.Gtk.Container+ContainerChild
        Gtk.Alignment w164 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w165 = new Gtk.HBox();
        w165.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w166 = new Gtk.Image();
        w166.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w165.Add(w166);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w168 = new Gtk.Label();
        w165.Add(w168);
        w164.Add(w165);
        this.removeButton8.Add(w164);
        this.filebox8.Add(this.removeButton8);
        Gtk.Box.BoxChild w172 = ((Gtk.Box.BoxChild)(this.filebox8[this.removeButton8]));
        w172.Position = 2;
        w172.Expand = false;
        w172.Fill = false;
        // Container child filebox8.Gtk.Box+BoxChild
        this.addButton8 = new Gtk.Button();
        this.addButton8.CanFocus = true;
        this.addButton8.Name = "addButton8";
        this.addButton8.UseUnderline = true;
        // Container child addButton8.Gtk.Container+ContainerChild
        Gtk.Alignment w173 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w174 = new Gtk.HBox();
        w174.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w175 = new Gtk.Image();
        w175.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w174.Add(w175);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w177 = new Gtk.Label();
        w174.Add(w177);
        w173.Add(w174);
        this.addButton8.Add(w173);
        this.filebox8.Add(this.addButton8);
        Gtk.Box.BoxChild w181 = ((Gtk.Box.BoxChild)(this.filebox8[this.addButton8]));
        w181.Position = 3;
        w181.Expand = false;
        w181.Fill = false;
        w181.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox8);
        Gtk.Box.BoxChild w182 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox8]));
        w182.Position = 10;
        w182.Expand = false;
        w182.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox9 = new Gtk.HBox();
        this.filebox9.Name = "filebox9";
        this.filebox9.Spacing = 6;
        // Container child filebox9.Gtk.Box+BoxChild
        this.fileLabel9 = new Gtk.Label();
        this.fileLabel9.WidthRequest = 40;
        this.fileLabel9.Name = "fileLabel9";
        this.fileLabel9.LabelProp = Mono.Unix.Catalog.GetString("File 9");
        this.filebox9.Add(this.fileLabel9);
        Gtk.Box.BoxChild w183 = ((Gtk.Box.BoxChild)(this.filebox9[this.fileLabel9]));
        w183.Position = 0;
        w183.Expand = false;
        w183.Fill = false;
        w183.Padding = ((uint)(6));
        // Container child filebox9.Gtk.Box+BoxChild
        this.eventbox9 = new Gtk.EventBox();
        this.eventbox9.Name = "eventbox9";
        // Container child eventbox9.Gtk.Container+ContainerChild
        this.file9 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file9.TooltipMarkup = "Drag & drop here";
        this.file9.WidthRequest = 180;
        this.file9.Name = "file9";
        this.eventbox9.Add(this.file9);
        this.filebox9.Add(this.eventbox9);
        Gtk.Box.BoxChild w185 = ((Gtk.Box.BoxChild)(this.filebox9[this.eventbox9]));
        w185.Position = 1;
        // Container child filebox9.Gtk.Box+BoxChild
        this.removeButton9 = new Gtk.Button();
        this.removeButton9.CanFocus = true;
        this.removeButton9.Name = "removeButton9";
        this.removeButton9.UseUnderline = true;
        // Container child removeButton9.Gtk.Container+ContainerChild
        Gtk.Alignment w186 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w187 = new Gtk.HBox();
        w187.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w188 = new Gtk.Image();
        w188.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w187.Add(w188);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w190 = new Gtk.Label();
        w187.Add(w190);
        w186.Add(w187);
        this.removeButton9.Add(w186);
        this.filebox9.Add(this.removeButton9);
        Gtk.Box.BoxChild w194 = ((Gtk.Box.BoxChild)(this.filebox9[this.removeButton9]));
        w194.Position = 2;
        w194.Expand = false;
        w194.Fill = false;
        // Container child filebox9.Gtk.Box+BoxChild
        this.addButton9 = new Gtk.Button();
        this.addButton9.CanFocus = true;
        this.addButton9.Name = "addButton9";
        this.addButton9.UseUnderline = true;
        // Container child addButton9.Gtk.Container+ContainerChild
        Gtk.Alignment w195 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w196 = new Gtk.HBox();
        w196.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w197 = new Gtk.Image();
        w197.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w196.Add(w197);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w199 = new Gtk.Label();
        w196.Add(w199);
        w195.Add(w196);
        this.addButton9.Add(w195);
        this.filebox9.Add(this.addButton9);
        Gtk.Box.BoxChild w203 = ((Gtk.Box.BoxChild)(this.filebox9[this.addButton9]));
        w203.Position = 3;
        w203.Expand = false;
        w203.Fill = false;
        w203.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox9);
        Gtk.Box.BoxChild w204 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox9]));
        w204.Position = 11;
        w204.Expand = false;
        w204.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.filebox10 = new Gtk.HBox();
        this.filebox10.Name = "filebox10";
        this.filebox10.Spacing = 6;
        // Container child filebox10.Gtk.Box+BoxChild
        this.fileLabel10 = new Gtk.Label();
        this.fileLabel10.WidthRequest = 40;
        this.fileLabel10.Name = "fileLabel10";
        this.fileLabel10.LabelProp = Mono.Unix.Catalog.GetString("File 10");
        this.filebox10.Add(this.fileLabel10);
        Gtk.Box.BoxChild w205 = ((Gtk.Box.BoxChild)(this.filebox10[this.fileLabel10]));
        w205.Position = 0;
        w205.Expand = false;
        w205.Fill = false;
        w205.Padding = ((uint)(6));
        // Container child filebox10.Gtk.Box+BoxChild
        this.eventbox10 = new Gtk.EventBox();
        this.eventbox10.Name = "eventbox10";
        // Container child eventbox10.Gtk.Container+ContainerChild
        this.file10 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.file10.TooltipMarkup = "Drag & drop here";
        this.file10.WidthRequest = 180;
        this.file10.Name = "file10";
        this.eventbox10.Add(this.file10);
        this.filebox10.Add(this.eventbox10);
        Gtk.Box.BoxChild w207 = ((Gtk.Box.BoxChild)(this.filebox10[this.eventbox10]));
        w207.Position = 1;
        // Container child filebox10.Gtk.Box+BoxChild
        this.removeButton10 = new Gtk.Button();
        this.removeButton10.CanFocus = true;
        this.removeButton10.Name = "removeButton10";
        this.removeButton10.UseUnderline = true;
        // Container child removeButton10.Gtk.Container+ContainerChild
        Gtk.Alignment w208 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w209 = new Gtk.HBox();
        w209.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w210 = new Gtk.Image();
        w210.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w209.Add(w210);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w212 = new Gtk.Label();
        w209.Add(w212);
        w208.Add(w209);
        this.removeButton10.Add(w208);
        this.filebox10.Add(this.removeButton10);
        Gtk.Box.BoxChild w216 = ((Gtk.Box.BoxChild)(this.filebox10[this.removeButton10]));
        w216.Position = 2;
        w216.Expand = false;
        w216.Fill = false;
        // Container child filebox10.Gtk.Box+BoxChild
        this.addButton10 = new Gtk.Button();
        this.addButton10.Sensitive = false;
        this.addButton10.CanFocus = true;
        this.addButton10.Name = "addButton10";
        this.addButton10.UseUnderline = true;
        // Container child addButton10.Gtk.Container+ContainerChild
        Gtk.Alignment w217 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w218 = new Gtk.HBox();
        w218.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w219 = new Gtk.Image();
        w219.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w218.Add(w219);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w221 = new Gtk.Label();
        w218.Add(w221);
        w217.Add(w218);
        this.addButton10.Add(w217);
        this.filebox10.Add(this.addButton10);
        Gtk.Box.BoxChild w225 = ((Gtk.Box.BoxChild)(this.filebox10[this.addButton10]));
        w225.Position = 3;
        w225.Expand = false;
        w225.Fill = false;
        w225.Padding = ((uint)(6));
        this.vbox1.Add(this.filebox10);
        Gtk.Box.BoxChild w226 = ((Gtk.Box.BoxChild)(this.vbox1[this.filebox10]));
        w226.Position = 12;
        w226.Expand = false;
        w226.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.spacer4 = new Gtk.Label();
        this.spacer4.Name = "spacer4";
        this.spacer4.LabelProp = Mono.Unix.Catalog.GetString("label20");
        this.vbox1.Add(this.spacer4);
        Gtk.Box.BoxChild w227 = ((Gtk.Box.BoxChild)(this.vbox1[this.spacer4]));
        w227.Position = 13;
        w227.Expand = false;
        w227.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox20 = new Gtk.HBox();
        this.hbox20.Name = "hbox20";
        this.hbox20.Spacing = 6;
        // Container child hbox20.Gtk.Box+BoxChild
        this.mergeOptionsLabel = new Gtk.Label();
        this.mergeOptionsLabel.Name = "mergeOptionsLabel";
        this.mergeOptionsLabel.LabelProp = Mono.Unix.Catalog.GetString("Merge options");
        this.hbox20.Add(this.mergeOptionsLabel);
        Gtk.Box.BoxChild w228 = ((Gtk.Box.BoxChild)(this.hbox20[this.mergeOptionsLabel]));
        w228.Position = 0;
        w228.Expand = false;
        w228.Fill = false;
        w228.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox20);
        Gtk.Box.BoxChild w229 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox20]));
        w229.Position = 14;
        w229.Expand = false;
        w229.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox21 = new Gtk.HBox();
        this.hbox21.Name = "hbox21";
        this.hbox21.Spacing = 6;
        // Container child hbox21.Gtk.Box+BoxChild
        this.hseparator3 = new Gtk.HSeparator();
        this.hseparator3.Name = "hseparator3";
        this.hbox21.Add(this.hseparator3);
        Gtk.Box.BoxChild w230 = ((Gtk.Box.BoxChild)(this.hbox21[this.hseparator3]));
        w230.Position = 0;
        w230.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox21);
        Gtk.Box.BoxChild w231 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox21]));
        w231.Position = 15;
        w231.Expand = false;
        w231.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox31 = new Gtk.HBox();
        this.hbox31.Name = "hbox31";
        this.hbox31.Spacing = 6;
        // Container child hbox31.Gtk.Box+BoxChild
        this.additionalLabel = new Gtk.Label();
        this.additionalLabel.Name = "additionalLabel";
        this.additionalLabel.LabelProp = Mono.Unix.Catalog.GetString("Additional audio track");
        this.hbox31.Add(this.additionalLabel);
        Gtk.Box.BoxChild w232 = ((Gtk.Box.BoxChild)(this.hbox31[this.additionalLabel]));
        w232.Position = 0;
        w232.Expand = false;
        w232.Fill = false;
        w232.Padding = ((uint)(6));
        // Container child hbox31.Gtk.Box+BoxChild
        this.eventbox11 = new Gtk.EventBox();
        this.eventbox11.Name = "eventbox11";
        // Container child eventbox11.Gtk.Container+ContainerChild
        this.filechooserbutton20 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton20.Name = "filechooserbutton20";
        this.eventbox11.Add(this.filechooserbutton20);
        this.hbox31.Add(this.eventbox11);
        Gtk.Box.BoxChild w234 = ((Gtk.Box.BoxChild)(this.hbox31[this.eventbox11]));
        w234.Position = 1;
        w234.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox31);
        Gtk.Box.BoxChild w235 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox31]));
        w235.Position = 16;
        w235.Expand = false;
        w235.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox32 = new Gtk.HBox();
        this.hbox32.Name = "hbox32";
        this.hbox32.Spacing = 6;
        // Container child hbox32.Gtk.Box+BoxChild
        this.inputAudioLabel = new Gtk.Label();
        this.inputAudioLabel.Name = "inputAudioLabel";
        this.inputAudioLabel.LabelProp = Mono.Unix.Catalog.GetString("Input audio track");
        this.hbox32.Add(this.inputAudioLabel);
        Gtk.Box.BoxChild w236 = ((Gtk.Box.BoxChild)(this.hbox32[this.inputAudioLabel]));
        w236.Position = 0;
        w236.Expand = false;
        w236.Fill = false;
        w236.Padding = ((uint)(6));
        // Container child hbox32.Gtk.Box+BoxChild
        this.inputAudioIndex = new Gtk.SpinButton(0, 4, 1);
        this.inputAudioIndex.CanFocus = true;
        this.inputAudioIndex.Name = "inputAudioIndex";
        this.inputAudioIndex.Adjustment.PageIncrement = 10;
        this.inputAudioIndex.ClimbRate = 1;
        this.inputAudioIndex.Numeric = true;
        this.hbox32.Add(this.inputAudioIndex);
        Gtk.Box.BoxChild w237 = ((Gtk.Box.BoxChild)(this.hbox32[this.inputAudioIndex]));
        w237.Position = 1;
        w237.Expand = false;
        w237.Fill = false;
        // Container child hbox32.Gtk.Box+BoxChild
        this.outputAudioIndex = new Gtk.SpinButton(0, 4, 1);
        this.outputAudioIndex.CanFocus = true;
        this.outputAudioIndex.Name = "outputAudioIndex";
        this.outputAudioIndex.Adjustment.PageIncrement = 10;
        this.outputAudioIndex.ClimbRate = 1;
        this.outputAudioIndex.Numeric = true;
        this.hbox32.Add(this.outputAudioIndex);
        Gtk.Box.BoxChild w238 = ((Gtk.Box.BoxChild)(this.hbox32[this.outputAudioIndex]));
        w238.PackType = ((Gtk.PackType)(1));
        w238.Position = 3;
        w238.Expand = false;
        w238.Fill = false;
        w238.Padding = ((uint)(6));
        // Container child hbox32.Gtk.Box+BoxChild
        this.outputAudioLabel = new Gtk.Label();
        this.outputAudioLabel.Name = "outputAudioLabel";
        this.outputAudioLabel.LabelProp = Mono.Unix.Catalog.GetString("Output audio track");
        this.hbox32.Add(this.outputAudioLabel);
        Gtk.Box.BoxChild w239 = ((Gtk.Box.BoxChild)(this.hbox32[this.outputAudioLabel]));
        w239.PackType = ((Gtk.PackType)(1));
        w239.Position = 4;
        w239.Expand = false;
        w239.Fill = false;
        this.vbox1.Add(this.hbox32);
        Gtk.Box.BoxChild w240 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox32]));
        w240.Position = 17;
        w240.Expand = false;
        w240.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.spacer5 = new Gtk.Label();
        this.spacer5.Name = "spacer5";
        this.spacer5.LabelProp = Mono.Unix.Catalog.GetString("label20");
        this.vbox1.Add(this.spacer5);
        Gtk.Box.BoxChild w241 = ((Gtk.Box.BoxChild)(this.vbox1[this.spacer5]));
        w241.Position = 18;
        w241.Expand = false;
        w241.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox22 = new Gtk.HBox();
        this.hbox22.Name = "hbox22";
        this.hbox22.Spacing = 6;
        // Container child hbox22.Gtk.Box+BoxChild
        this.outputFileLabel = new Gtk.Label();
        this.outputFileLabel.Name = "outputFileLabel";
        this.outputFileLabel.LabelProp = Mono.Unix.Catalog.GetString("Merge");
        this.hbox22.Add(this.outputFileLabel);
        Gtk.Box.BoxChild w242 = ((Gtk.Box.BoxChild)(this.hbox22[this.outputFileLabel]));
        w242.Position = 0;
        w242.Expand = false;
        w242.Fill = false;
        w242.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox22);
        Gtk.Box.BoxChild w243 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox22]));
        w243.Position = 19;
        w243.Expand = false;
        w243.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox23 = new Gtk.HBox();
        this.hbox23.Name = "hbox23";
        this.hbox23.Spacing = 6;
        // Container child hbox23.Gtk.Box+BoxChild
        this.hseparator4 = new Gtk.HSeparator();
        this.hseparator4.Name = "hseparator4";
        this.hbox23.Add(this.hseparator4);
        Gtk.Box.BoxChild w244 = ((Gtk.Box.BoxChild)(this.hbox23[this.hseparator4]));
        w244.Position = 0;
        w244.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox23);
        Gtk.Box.BoxChild w245 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox23]));
        w245.Position = 20;
        w245.Expand = false;
        w245.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox26 = new Gtk.HBox();
        this.hbox26.Name = "hbox26";
        this.hbox26.Spacing = 6;
        // Container child hbox26.Gtk.Box+BoxChild
        this.mergeActionButton = new Gtk.Button();
        this.mergeActionButton.CanFocus = true;
        this.mergeActionButton.Name = "mergeActionButton";
        this.mergeActionButton.UseUnderline = true;
        // Container child mergeActionButton.Gtk.Container+ContainerChild
        Gtk.Alignment w246 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w247 = new Gtk.HBox();
        w247.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w248 = new Gtk.Image();
        w248.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
        w247.Add(w248);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w250 = new Gtk.Label();
        w250.LabelProp = Mono.Unix.Catalog.GetString(" Merge");
        w250.UseUnderline = true;
        w247.Add(w250);
        w246.Add(w247);
        this.mergeActionButton.Add(w246);
        this.hbox26.Add(this.mergeActionButton);
        Gtk.Box.BoxChild w254 = ((Gtk.Box.BoxChild)(this.hbox26[this.mergeActionButton]));
        w254.Position = 0;
        w254.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox26);
        Gtk.Box.BoxChild w255 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox26]));
        w255.Position = 21;
        w255.Expand = false;
        w255.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.spacer6 = new Gtk.Label();
        this.spacer6.Name = "spacer6";
        this.spacer6.LabelProp = Mono.Unix.Catalog.GetString("label20");
        this.vbox1.Add(this.spacer6);
        Gtk.Box.BoxChild w256 = ((Gtk.Box.BoxChild)(this.vbox1[this.spacer6]));
        w256.Position = 22;
        w256.Expand = false;
        w256.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox28 = new Gtk.HBox();
        this.hbox28.Name = "hbox28";
        this.hbox28.Spacing = 6;
        // Container child hbox28.Gtk.Box+BoxChild
        this.progressLabel = new Gtk.Label();
        this.progressLabel.Name = "progressLabel";
        this.progressLabel.LabelProp = Mono.Unix.Catalog.GetString("Progress");
        this.hbox28.Add(this.progressLabel);
        Gtk.Box.BoxChild w257 = ((Gtk.Box.BoxChild)(this.hbox28[this.progressLabel]));
        w257.Position = 0;
        w257.Expand = false;
        w257.Fill = false;
        w257.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox28);
        Gtk.Box.BoxChild w258 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox28]));
        w258.Position = 23;
        w258.Expand = false;
        w258.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox29 = new Gtk.HBox();
        this.hbox29.Name = "hbox29";
        this.hbox29.Spacing = 6;
        // Container child hbox29.Gtk.Box+BoxChild
        this.hseparator7 = new Gtk.HSeparator();
        this.hseparator7.Name = "hseparator7";
        this.hbox29.Add(this.hseparator7);
        Gtk.Box.BoxChild w259 = ((Gtk.Box.BoxChild)(this.hbox29[this.hseparator7]));
        w259.Position = 0;
        w259.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox29);
        Gtk.Box.BoxChild w260 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox29]));
        w260.Position = 24;
        w260.Expand = false;
        w260.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox30 = new Gtk.HBox();
        this.hbox30.Name = "hbox30";
        this.hbox30.Spacing = 6;
        // Container child hbox30.Gtk.Box+BoxChild
        this.mergeProgressBar1 = new Gtk.ProgressBar();
        this.mergeProgressBar1.Name = "mergeProgressBar1";
        this.hbox30.Add(this.mergeProgressBar1);
        Gtk.Box.BoxChild w261 = ((Gtk.Box.BoxChild)(this.hbox30[this.mergeProgressBar1]));
        w261.Position = 0;
        w261.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox30);
        Gtk.Box.BoxChild w262 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox30]));
        w262.Position = 25;
        w262.Expand = false;
        w262.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.spacer7 = new Gtk.Label();
        this.spacer7.Name = "spacer7";
        this.spacer7.LabelProp = Mono.Unix.Catalog.GetString("label20");
        this.vbox1.Add(this.spacer7);
        Gtk.Box.BoxChild w263 = ((Gtk.Box.BoxChild)(this.vbox1[this.spacer7]));
        w263.Position = 26;
        w263.Expand = false;
        w263.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 528;
        this.DefaultHeight = 668;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.file1.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton1.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton1.Clicked += new System.EventHandler(this.addFileButton);
        this.file2.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton2.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton2.Clicked += new System.EventHandler(this.addFileButton);
        this.file3.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton3.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton3.Clicked += new System.EventHandler(this.addFileButton);
        this.file4.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton4.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton4.Clicked += new System.EventHandler(this.addFileButton);
        this.file5.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton5.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton5.Clicked += new System.EventHandler(this.addFileButton);
        this.file6.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton6.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton6.Clicked += new System.EventHandler(this.addFileButton);
        this.file7.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton7.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton7.Clicked += new System.EventHandler(this.addFileButton);
        this.file8.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton8.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton8.Clicked += new System.EventHandler(this.addFileButton);
        this.file9.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton9.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton9.Clicked += new System.EventHandler(this.addFileButton);
        this.file10.CurrentFolderChanged += new System.EventHandler(this.OnCurrentFolderChanged);
        this.removeButton10.Clicked += new System.EventHandler(this.removeFileButton);
        this.addButton10.Clicked += new System.EventHandler(this.addFileButton);
        this.mergeActionButton.Clicked += new System.EventHandler(this.OnMergeActionButtonClicked);
    }
}
